"""Update favorite products table

Revision ID: be35092d1c6a
Revises: e7642fcb8c04
Create Date: 2020-10-10 21:17:50.833344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be35092d1c6a"
down_revision = "e7642fcb8c04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients_favorite_product", sa.Column("external_id", postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients_favorite_product", "external_id")
    # ### end Alembic commands ###
