"""Add clients table

Revision ID: e4b53fb36062
Revises: 1595f4d4b09a
Create Date: 2020-10-09 20:49:08.140571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4b53fb36062"
down_revision = "1595f4d4b09a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
